# Database of 50 standard sentence pairs and their semantic features
import re

DATABASE = [
    {
        "id": 1,
        "english": "I am reading a book.",
        "isl": "ME BOOK READ",
        "type": "Statement",
        "subject": "me",
        "action": "read",
        "object": "book",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "SOV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Basic SOV order"
    },
    {
        "id": 2,
        "english": "My brother works at the hospital.",
        "isl": "MY BROTHER HOSPITAL WORK",
        "type": "Statement",
        "subject": "brother",
        "action": "work",
        "object": "",
        "time": "",
        "location": "hospital",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "my",
        "grammar_pattern": "SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Basic SQV order"
    },
    {
        "id": 3,
        "english": "She will buy a new car tomorrow.",
        "isl": "TOMORROW SHE CAR NEW BUY",
        "type": "Statement",
        "subject": "she",
        "action": "buy",
        "object": "car",
        "time": "tomorrow",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "new",
        "grammar_pattern": "Time + SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Time marker first"
    },
    {
        "id": 4,
        "english": "The cat is sleeping on the table.",
        "isl": "TABLE CAT SLEEP",
        "type": "Statement",
        "subject": "cat",
        "action": "sleep",
        "object": "",
        "time": "",
        "location": "table",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Locative + SV",
        "source": "Academic",
        "confidence": "High",
        "notes": "Location established first"
    },
    {
        "id": 5,
        "english": "They played cricket yesterday.",
        "isl": "YESTERDAY THEY CRICKET PLAY",
        "type": "Statement",
        "subject": "they",
        "action": "play",
        "object": "cricket",
        "time": "yesterday",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Time + SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Time marker first"
    },
    {
        "id": 6,
        "english": "The teacher is writing on the board.",
        "isl": "TEACHER BOARD WRITE",
        "type": "Statement",
        "subject": "teacher",
        "action": "write",
        "object": "",
        "time": "",
        "location": "board",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Basic SQV order"
    },
    {
        "id": 7,
        "english": "I like hot coffee.",
        "isl": "ME COFFEE HOT LIKE",
        "type": "Statement",
        "subject": "me",
        "action": "like",
        "object": "coffee",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "hot",
        "grammar_pattern": "SQV",
        "source": "Academic",
        "confidence": "High",
        "notes": "Adjective follows noun"
    },
    {
        "id": 8,
        "english": "He gave me an apple.",
        "isl": "HE APPLE GIVE-ME",
        "type": "Statement",
        "subject": "he",
        "action": "give",
        "object": "apple",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "me",
        "attributes": "",
        "grammar_pattern": "SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Directional verb used"
    },
    {
        "id": 9,
        "english": "My mother cooks food every day.",
        "isl": "EVERYDAY MY MOTHER FOOD COOK",
        "type": "Statement",
        "subject": "mother",
        "action": "cook",
        "object": "food",
        "time": "every day",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "my",
        "grammar_pattern": "Time + SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Time marker first"
    },
    {
        "id": 10,
        "english": "The train arrived late.",
        "isl": "TRAIN LATE ARRIVE",
        "type": "Statement",
        "subject": "train",
        "action": "arrive",
        "object": "",
        "time": "late",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "SQV",
        "source": "Academic",
        "confidence": "High",
        "notes": "Adverb placement"
    },
    {
        "id": 11,
        "english": "We are going to the market now.",
        "isl": "NOW WE MARKET GO",
        "type": "Statement",
        "subject": "we",
        "action": "go",
        "object": "",
        "time": "now",
        "location": "market",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Time + SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Time marker first"
    },
    {
        "id": 12,
        "english": "The red flower is beautiful.",
        "isl": "FLOWER RED BEAUTIFUL",
        "type": "Statement",
        "subject": "flower",
        "action": "",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "red, beautiful",
        "grammar_pattern": "SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Adjective follows noun"
    },
    {
        "id": 13,
        "english": "His sister is a doctor.",
        "isl": "HIS SISTER DOCTOR",
        "type": "Statement",
        "subject": "sister",
        "action": "doctor",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "his",
        "grammar_pattern": "SQV",
        "source": "Academic",
        "confidence": "High",
        "notes": "English copula dropped"
    },
    {
        "id": 14,
        "english": "I saw a dog running.",
        "isl": "ME DOG RUN SEE",
        "type": "Statement",
        "subject": "me",
        "action": "see",
        "object": "dog",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "running",
        "grammar_pattern": "SQV",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Action observed at end"
    },
    {
        "id": 15,
        "english": "The baby is crying loudly.",
        "isl": "BABY LOUD CRY",
        "type": "Statement",
        "subject": "baby",
        "action": "cry",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "loudly",
        "grammar_pattern": "SQV",
        "source": "Academic",
        "confidence": "High",
        "notes": "Adverb precedes verb"
    },
    {
        "id": 16,
        "english": "What is your name?",
        "isl": "YOUR NAME WHAT",
        "type": "Question",
        "subject": "you",
        "action": "",
        "object": "name",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "What",
        "target": "",
        "attributes": "your",
        "grammar_pattern": "Question-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 17,
        "english": "Where are you going?",
        "isl": "YOU GO WHERE",
        "type": "Question",
        "subject": "you",
        "action": "go",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Where",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Question-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 18,
        "english": "When will the class start?",
        "isl": "CLASS START WHEN",
        "type": "Question",
        "subject": "class",
        "action": "start",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "When",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Question-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 19,
        "english": "Why is the baby crying?",
        "isl": "BABY CRY WHY",
        "type": "Question",
        "subject": "baby",
        "action": "cry",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Why",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Question-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 20,
        "english": "How did you come here?",
        "isl": "YOU COME HERE HOW",
        "type": "Question",
        "subject": "you",
        "action": "come",
        "object": "",
        "time": "",
        "location": "here",
        "intent": "Ask",
        "negation": False,
        "question_type": "How",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Question-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 21,
        "english": "Who is that man?",
        "isl": "THAT MAN WHO",
        "type": "Question",
        "subject": "man",
        "action": "",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Who",
        "target": "",
        "attributes": "that",
        "grammar_pattern": "Question-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 22,
        "english": "Which book do you want?",
        "isl": "YOU BOOK WANT WHICH",
        "type": "Question",
        "subject": "you",
        "action": "want",
        "object": "book",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Which",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Question-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 23,
        "english": "How much does this shirt cost?",
        "isl": "THIS SHIRT COST HOW-MUCH",
        "type": "Question",
        "subject": "shirt",
        "action": "cost",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "How much",
        "target": "",
        "attributes": "this",
        "grammar_pattern": "Question-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 24,
        "english": "Whose pen is this?",
        "isl": "THIS PEN WHOSE",
        "type": "Question",
        "subject": "pen",
        "action": "",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Whose",
        "target": "",
        "attributes": "this",
        "grammar_pattern": "Question-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Wh-word last + furrowed brows"
    },
    {
        "id": 25,
        "english": "Are you hungry?",
        "isl": "YOU HUNGRY",
        "type": "Question",
        "subject": "you",
        "action": "",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "hungry",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Raised brows, head tilt"
    },
    {
        "id": 26,
        "english": "Did you finish your homework?",
        "isl": "YOUR HOMEWORK FINISH",
        "type": "Question",
        "subject": "you",
        "action": "finish",
        "object": "homework",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "your",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "Academic",
        "confidence": "High",
        "notes": "Raised brows, head tilt"
    },
    {
        "id": 27,
        "english": "Do you like playing cricket?",
        "isl": "YOU CRICKET PLAY LIKE",
        "type": "Question",
        "subject": "you",
        "action": "like",
        "object": "cricket",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "playing",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Raised brows, head tilt"
    },
    {
        "id": 28,
        "english": "Are we going to the movie tomorrow?",
        "isl": "TOMORROW WE MOVIE GO",
        "type": "Question",
        "subject": "we",
        "action": "go",
        "object": "",
        "time": "tomorrow",
        "location": "movie",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "Academic",
        "confidence": "High",
        "notes": "Time first + Raised brows"
    },
    {
        "id": 29,
        "english": "Is your house big?",
        "isl": "YOUR HOUSE BIG",
        "type": "Question",
        "subject": "house",
        "action": "",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "your, big",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Raised brows, head tilt"
    },
    {
        "id": 30,
        "english": "Have you seen my brother?",
        "isl": "YOU MY BROTHER SEE",
        "type": "Question",
        "subject": "you",
        "action": "see",
        "object": "brother",
        "time": "",
        "location": "",
        "intent": "Ask",
        "negation": False,
        "question_type": "Yes/No",
        "target": "",
        "attributes": "my",
        "grammar_pattern": "Yes/No (NMS)",
        "source": "Academic",
        "confidence": "High",
        "notes": "Raised brows, head tilt"
    },
    {
        "id": 31,
        "english": "Please give me some water.",
        "isl": "WATER GIVE-ME",
        "type": "Request",
        "subject": "you",
        "action": "give",
        "object": "water",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "me",
        "attributes": "some",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Softer sign + Namaste"
    },
    {
        "id": 32,
        "english": "Can you help me, please?",
        "isl": "YOU HELP-ME",
        "type": "Request",
        "subject": "you",
        "action": "help",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "me",
        "attributes": "",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "Academic",
        "confidence": "High",
        "notes": "Directional verb + polite NMS"
    },
    {
        "id": 33,
        "english": "Please write your name here.",
        "isl": "YOUR NAME HERE WRITE",
        "type": "Request",
        "subject": "you",
        "action": "write",
        "object": "name",
        "time": "",
        "location": "here",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "your",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Polite NMS + soft speed"
    },
    {
        "id": 34,
        "english": "Wait a minute, please.",
        "isl": "WAIT ONE-MINUTE",
        "type": "Request",
        "subject": "you",
        "action": "wait",
        "object": "",
        "time": "minute",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "one",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "Academic",
        "confidence": "High",
        "notes": "Polite NMS + soft speed"
    },
    {
        "id": 35,
        "english": "Please sit down.",
        "isl": "SIT",
        "type": "Request",
        "subject": "you",
        "action": "sit",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "down",
        "grammar_pattern": "Verb + Polite NMS",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Softer movement"
    },
    {
        "id": 36,
        "english": "Please explain this again.",
        "isl": "THIS AGAIN EXPLAIN",
        "type": "Request",
        "subject": "you",
        "action": "explain",
        "object": "this",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "again",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "Academic",
        "confidence": "High",
        "notes": "Polite NMS + soft speed"
    },
    {
        "id": 37,
        "english": "Open the window, please.",
        "isl": "WINDOW OPEN",
        "type": "Request",
        "subject": "you",
        "action": "open",
        "object": "window",
        "time": "",
        "location": "",
        "intent": "Command",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Polite NMS + soft speed"
    },
    {
        "id": 38,
        "english": "Please walk slowly.",
        "isl": "WALK SLOW",
        "type": "Request",
        "subject": "you",
        "action": "walk",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "",
        "attributes": "slowly",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "Academic",
        "confidence": "High",
        "notes": "Polite NMS + soft speed"
    },
    {
        "id": 39,
        "english": "Can you show me the way?",
        "isl": "WAY SHOW-ME",
        "type": "Request",
        "subject": "you",
        "action": "show",
        "object": "way",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "me",
        "attributes": "",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Directional verb + polite NMS"
    },
    {
        "id": 40,
        "english": "Please pass the book to me.",
        "isl": "BOOK PASS-ME",
        "type": "Request",
        "subject": "you",
        "action": "pass",
        "object": "book",
        "time": "",
        "location": "",
        "intent": "Request",
        "negation": False,
        "question_type": "",
        "target": "me",
        "attributes": "",
        "grammar_pattern": "SQV + Polite NMS",
        "source": "Academic",
        "confidence": "High",
        "notes": "Directional verb + polite NMS"
    },
    {
        "id": 41,
        "english": "I don't know him.",
        "isl": "ME HIM KNOW NOT",
        "type": "Negation",
        "subject": "me",
        "action": "know",
        "object": "",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "him",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "NOT sign at end"
    },
    {
        "id": 42,
        "english": "She is not coming tomorrow.",
        "isl": "TOMORROW SHE COME NOT",
        "type": "Negation",
        "subject": "she",
        "action": "come",
        "object": "",
        "time": "tomorrow",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "Time first + NOT sign"
    },
    {
        "id": 43,
        "english": "I do not like tea.",
        "isl": "ME TEA LIKE",
        "type": "Negation",
        "subject": "me",
        "action": "like",
        "object": "tea",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Verb + Headshake",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Headshake during verb"
    },
    {
        "id": 44,
        "english": "We have no money.",
        "isl": "WE MONEY HAVE-NOT",
        "type": "Negation",
        "subject": "we",
        "action": "have",
        "object": "money",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "no",
        "grammar_pattern": "Built-in negative",
        "source": "Academic",
        "confidence": "High",
        "notes": "Unique have-not sign"
    },
    {
        "id": 45,
        "english": "The shop is not open today.",
        "isl": "TODAY SHOP OPEN NOT",
        "type": "Negation",
        "subject": "shop",
        "action": "",
        "object": "",
        "time": "today",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "open",
        "grammar_pattern": "Negation-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Time first + NOT sign"
    },
    {
        "id": 46,
        "english": "He did not eat the apple.",
        "isl": "HE APPLE EAT NOT",
        "type": "Negation",
        "subject": "he",
        "action": "eat",
        "object": "apple",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "NOT sign at end"
    },
    {
        "id": 47,
        "english": "I don't want to go there.",
        "isl": "ME THERE GO DON'T-WANT",
        "type": "Negation",
        "subject": "me",
        "action": "want",
        "object": "",
        "time": "",
        "location": "there",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Built-in negative",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "Unique don't-want sign"
    },
    {
        "id": 48,
        "english": "You should not run here.",
        "isl": "YOU HERE RUN NOT",
        "type": "Negation",
        "subject": "you",
        "action": "run",
        "object": "",
        "time": "",
        "location": "here",
        "intent": "Command",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "NOT sign at end"
    },
    {
        "id": 49,
        "english": "I don't have a pen.",
        "isl": "ME PEN HAVE NOT",
        "type": "Negation",
        "subject": "me",
        "action": "have",
        "object": "pen",
        "time": "",
        "location": "",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "ISLRTC",
        "confidence": "High",
        "notes": "NOT sign at end"
    },
    {
        "id": 50,
        "english": "It is not raining outside.",
        "isl": "OUTSIDE RAIN NOT",
        "type": "Negation",
        "subject": "it",
        "action": "rain",
        "object": "",
        "time": "",
        "location": "outside",
        "intent": "Inform",
        "negation": True,
        "question_type": "",
        "target": "",
        "attributes": "",
        "grammar_pattern": "Negation-at-end",
        "source": "Academic",
        "confidence": "High",
        "notes": "NOT sign at end"
    }
]

def clean_sentence(text: str) -> str:
    if not text:
        return ""
    # remove punctuation and multiple spaces
    cleaned = text.lower().strip()
    cleaned = re.sub(r'[?.!,]', '', cleaned)
    cleaned = re.sub(r'\s+', ' ', cleaned)
    return cleaned.strip()

# Build lookups
english_to_db = {}
isl_to_db = {}

for item in DATABASE:
    # Key by cleaned English
    eng_key = clean_sentence(item["english"])
    english_to_db[eng_key] = item
    
    # Key by cleaned ISL
    isl_key = clean_sentence(item["isl"])
    isl_to_db[isl_key] = item

def get_standard_translation(text: str, mode: str) -> dict:
    cleaned = clean_sentence(text)
    if mode == "english_to_isl":
        if cleaned in english_to_db:
            item = english_to_db[cleaned]
            # Construct TranslationResponse format
            # We want token breakdowns
            tokens = item["isl"].split()
            token_breakdowns = []
            
            # Simple breakdown map helper based on standard columns
            for t in tokens:
                t_upper = t.upper()
                desc = ""
                cat = "other"
                
                # Check mapping for category
                if t_upper in [item["subject"].upper(), "ME", "WE", "YOU", "HE", "SHE", "THEY", "CAT", "TEACHER", "BROTHER", "SISTER", "BABY", "TRAIN", "FLOWER", "HOMEWORK", "SHOP", "IT", "SIT"]:
                    cat = "subject"
                    desc = "Subject"
                elif t_upper in [item["object"].upper(), "BOOK", "CAR", "CRICKET", "COFFEE", "APPLE", "FOOD", "MARKET", "NAME", "WATER", "WINDOW", "WAY", "TEA", "MONEY", "PEN"]:
                    cat = "object"
                    desc = "Object"
                elif t_upper in [item["action"].upper(), "READ", "WORK", "BUY", "SLEEP", "PLAY", "WRITE", "LIKE", "GIVE-ME", "COOK", "ARRIVE", "GO", "SEE", "CRY", "SIT", "EXPLAIN", "OPEN", "WALK", "SHOW-ME", "PASS-ME", "KNOW", "COME", "HAVE-NOT", "DON'T-WANT", "HAVE", "RAIN"]:
                    cat = "verb"
                    desc = "Verb"
                elif t_upper in [item["time"].upper(), "TOMORROW", "YESTERDAY", "EVERYDAY", "LATE", "NOW", "TODAY", "ONE-MINUTE"]:
                    cat = "time"
                    desc = "Time Marker"
                elif t_upper in [item["location"].upper(), "HOSPITAL", "TABLE", "BOARD", "MARKET", "HERE", "MOVIE", "OUTSIDE"]:
                    cat = "object"
                    desc = "Location"
                elif t_upper in ["NOT", "HAVE-NOT", "DON'T-WANT"]:
                    cat = "verb"
                    desc = "Negation"
                elif t_upper in ["WHAT", "WHERE", "WHEN", "WHY", "HOW", "WHO", "WHICH", "HOW-MUCH", "WHOSE"]:
                    cat = "question"
                    desc = f"Question Word ({t_upper})"
                else:
                    # check if modifier
                    cat = "modifier"
                    desc = "Modifier"
                token_breakdowns.append((t, cat, desc))
                
            return {
                "result": item["isl"],
                "time_markers": [item["time"].upper()] if item["time"] else [],
                "subjects": [item["subject"].upper()] if item["subject"] else [],
                "objects": [item["object"].upper()] if item["object"] else [],
                "verb_modifiers": [],
                "verbs": [item["action"].upper()] if item["action"] else [],
                "removed": [],
                "has_negation": item["negation"],
                "has_wh_word": item["question_type"].upper() if item["question_type"] and item["question_type"] != "Yes/No" else None,
                "is_question": item["type"] == "Question",
                "token_breakdowns": token_breakdowns
            }
    else: # isl_to_english
        if cleaned in isl_to_db:
            item = isl_to_db[cleaned]
            # Construct TranslationResponse format
            tokens = item["isl"].split()
            token_breakdowns = []
            
            for t in tokens:
                t_upper = t.upper()
                desc = ""
                cat = "other"
                
                # Check mapping for category
                if t_upper in [item["subject"].upper(), "ME", "WE", "YOU", "HE", "SHE", "THEY", "CAT", "TEACHER", "BROTHER", "SISTER", "BABY", "TRAIN", "FLOWER", "HOMEWORK", "SHOP", "IT", "SIT"]:
                    cat = "subject"
                    desc = "Subject"
                elif t_upper in [item["object"].upper(), "BOOK", "CAR", "CRICKET", "COFFEE", "APPLE", "FOOD", "MARKET", "NAME", "WATER", "WINDOW", "WAY", "TEA", "MONEY", "PEN"]:
                    cat = "object"
                    desc = "Object"
                elif t_upper in [item["action"].upper(), "READ", "WORK", "BUY", "SLEEP", "PLAY", "WRITE", "LIKE", "GIVE-ME", "COOK", "ARRIVE", "GO", "SEE", "CRY", "SIT", "EXPLAIN", "OPEN", "WALK", "SHOW-ME", "PASS-ME", "KNOW", "COME", "HAVE-NOT", "DON'T-WANT", "HAVE", "RAIN"]:
                    cat = "verb"
                    desc = "Verb"
                elif t_upper in [item["time"].upper(), "TOMORROW", "YESTERDAY", "EVERYDAY", "LATE", "NOW", "TODAY", "ONE-MINUTE"]:
                    cat = "time"
                    desc = "Time Marker"
                elif t_upper in [item["location"].upper(), "HOSPITAL", "TABLE", "BOARD", "MARKET", "HERE", "MOVIE", "OUTSIDE"]:
                    cat = "object"
                    desc = "Location"
                elif t_upper in ["NOT", "HAVE-NOT", "DON'T-WANT"]:
                    cat = "verb"
                    desc = "Negation"
                elif t_upper in ["WHAT", "WHERE", "WHEN", "WHY", "HOW", "WHO", "WHICH", "HOW-MUCH", "WHOSE"]:
                    cat = "question"
                    desc = f"Question Word ({t_upper})"
                else:
                    cat = "modifier"
                    desc = "Modifier"
                token_breakdowns.append((t, cat, desc))

            return {
                "result": item["english"],
                "time_markers": [item["time"].upper()] if item["time"] else [],
                "subjects": [item["subject"].upper()] if item["subject"] else [],
                "objects": [item["object"].upper()] if item["object"] else [],
                "verb_modifiers": [],
                "verbs": [item["action"].upper()] if item["action"] else [],
                "removed": [],
                "has_negation": item["negation"],
                "has_wh_word": item["question_type"].upper() if item["question_type"] and item["question_type"] != "Yes/No" else None,
                "is_question": item["type"] == "Question",
                "token_breakdowns": token_breakdowns
            }
    return None
